POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "eventstore-connector",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "mysql",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "root",
    "database.server.id": "184054",
    "database.allowPublicKeyRetrieval":"true",
    "database.server.name": "examination-command-service-db",
    "database.include.list": "eventstore",
    "database.history.kafka.bootstrap.servers": "kafka:9092",
    "database.history.kafka.topic": "dbhistory.eventstore",
    "include.schema.changes": "true"
  }
}