version: "3.8"
services:
  examination-command-service:
    image: examination_command_service
    container_name: examination-command-service
    ports:
      - "${EXAMINATION_COMMAND_SERVICE_PORT}:8080"

  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:2181"
      - "${ZOOKEEPER_REPLICA_1_PORT}:2888"
      - "${ZOOKEEPER_REPLICA_2_PORT}:3888"

  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: "kafka"
    depends_on:
      - zookeeper
    links:
      - "zookeeper:zookeeper"
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_CLIENT_PORT}

  mysql:
    image: mysql:8.0.31-debian
    container_name: "mysql"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/simpletask/Work/docker/volumes/microservice/mysql-ecs/scripts:/docker-entrypoint-initdb.d
      - /home/simpletask/Work/docker/volumes/microservice/mysql-ecs/data:/var/lib/mysql

  debezium_connector:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    container_name: debezium_connector
    ports:
      - "${DEBEZIUM_CONNECTOR_PORT}:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=kafka:${KAFKA_PORT}
    links:
      - "kafka:kafka"
      - "mysql:mysql"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:${KAFKA_PORT}

  debezium-ui:
    image: debezium/debezium-ui:${DEBEZIUM_VERSION}
    container_name: "debezium-ui"
    ports:
      - "${DEBEZIUM_UI_PORT}:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://debezium_connector:${DEBEZIUM_CONNECTOR_PORT}
